In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [3]:
dataset = pd.read_csv('binary_log.csv')

In [4]:
dataset

SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [5]:
dataset['Admitted'] = dataset['Admitted'].map({'Yes':1,'No':0})
dataset['Gender'] = dataset['Gender'].map({'Female':1,'Male':0})

In [6]:
dataset

SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

In [7]:
x = dataset.iloc[:,[0,2]].values

In [8]:
x

array([[1363,    0],
       [1792,    1],
       [1954,    1],
       [1653,    0],
       [1593,    0],
       [1755,    1],
       [1775,    1],
       [1887,    1],
       [1893,    1],
       [1580,    0],
       [1857,    1],
       [1880,    1],
       [1664,    1],
       [1364,    0],
       [1693,    0],
       [1850,    1],
       [1633,    0],
       [1634,    0],
       [1636,    1],
       [1855,    1],
       [1987,    1],
       [1997,    0],
       [1422,    1],
       [1508,    1],
       [1720,    1],
       [1879,    0],
       [1634,    1],
       [1802,    0],
       [1849,    1],
       [1764,    1],
       [1460,    0],
       [1675,    1],
       [1656,    0],
       [2020,    0],
       [1850,    0],
       [1865,    0],
       [1664,    0],
       [1872,    1],
       [1654,    0],
       [1393,    1],
       [1587,    0],
       [1631,    1],
       [1931,    0],
       [1370,    0],
       [1810,    0],
       [1414,    0],
       [1761,    1],
       [1477,

In [9]:
y = dataset.iloc[:,1].values

In [10]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train.shape

(134, 2)

In [14]:
x_test.shape

(34, 2)

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
model =  DecisionTreeClassifier()

In [18]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
# Evaluation

In [20]:
y_pred = model.predict(x_test)

In [21]:
y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [22]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix

In [24]:
print(confusion_matrix(y_test,y_pred))

[[15  0]
 [ 0 19]]


In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        19

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

