In [1]:
import numpy as np 

In [2]:
arr = np.array([3,45,67,23,67,89])

In [3]:
arr

array([ 3, 45, 67, 23, 67, 89])

In [4]:
arr.shape

(6,)

In [5]:
#(row,column)

In [6]:
arr1 = np.array([[2,3,4],[6,7,9]])

In [7]:
arr1

array([[2, 3, 4],
       [6, 7, 9]])

In [8]:
arr1.shape

(2, 3)

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,5,2)

array([0., 5.])

In [23]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [24]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [25]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [26]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.69567294, 0.1285098 , 0.01537291, 0.65767529, 0.94660327])

In [30]:
np.random.rand(3,4)

array([[0.63706038, 0.38797359, 0.59126161, 0.57257442],
       [0.19935715, 0.76943259, 0.34340865, 0.51574186],
       [0.66315799, 0.48610709, 0.87001513, 0.4313348 ]])

In [32]:
np.random.randint(1,100)

77

In [33]:
np.random.randint(1,100,20)

array([15, 10, 53, 21, 37, 27, 54, 17, 84, 50, 15, 38, 19, 57, 77, 77, 21,
       33, 80, 21])

In [34]:
test = np.random.randint(1,100,20)

In [35]:
test

array([30, 71,  4, 52, 36, 18, 18, 59, 39, 57, 93, 17, 52, 25, 82, 61, 36,
       12,  2, 80])

In [36]:
arr3 = np.arange(20)

In [37]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr3.shape

(20,)

In [39]:
arr3.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [40]:
arr3.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
arr3.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
arr3.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
arr3.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
arr3.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
arr4 = np.array([34,2,67,89,33,12,22,44])

In [46]:
arr4

array([34,  2, 67, 89, 33, 12, 22, 44])

In [47]:
arr4.shape

(8,)

In [48]:
arr4.max()

89

In [49]:
arr4.min()

2

In [50]:
arr4

array([34,  2, 67, 89, 33, 12, 22, 44])

In [51]:
arr4.argmax()

3

In [52]:
arr4.argmin()

1

In [53]:
arr4.dtype

dtype('int32')

In [54]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
arr1

array([[2, 3, 4],
       [6, 7, 9]])

In [57]:
arr5 = np.random.rand(4)

In [58]:
arr5

array([0.28581522, 0.45862575, 0.32732258, 0.92286568])

In [59]:
arr5.dtype

dtype('float64')

In [60]:
arr

array([ 3, 45, 67, 23, 67, 89])

In [61]:
arr6 = np.array([1,2,3,4,5])

In [62]:
arr6

array([1, 2, 3, 4, 5])

In [63]:
np.sqrt(arr6)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [64]:
np.exp(arr6)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [65]:
np.log(arr6)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [66]:
np.cos(arr6)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [67]:
np.sin(arr6)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [68]:
np.sum(arr6)

15

In [69]:
np.var(arr6)

2.0

In [70]:
np.mean(arr6)

3.0

In [71]:
np.sqrt(np.var(arr6))

1.4142135623730951