In [1]:
#user define function

In [2]:
def av(num):
    return num**2

In [3]:
type(av)

function

In [4]:
av(5)

25

In [5]:
av(4)

16

In [6]:
def add (a,b):
    c = a+b
    return c

In [7]:
add(34,56)

90

In [8]:
def addt(a,b,c):
        d = a+b+c
        return d
        

In [9]:
addt(3,4,7)

14

In [10]:
def add(a,b):
       return a+b

In [11]:
add(2,3)

5

In [12]:
#list Comprehensive

In [13]:
# allow to creat list from loop

In [16]:
x = [1,2,3,4]

In [17]:
out = []
for i in x:
    out.append(i**2)


In [18]:
out

[1, 4, 9, 16]

In [19]:
out1 = [i**2 for i in x]

In [20]:
out1

[1, 4, 9, 16]

In [21]:
out2 = [i**3 for i in x]

In [22]:
out2

[1, 8, 27, 64]

In [23]:
import numpy as np

In [24]:
my_list = [3,4,2,6,8,4]

In [25]:
my_list

[3, 4, 2, 6, 8, 4]

In [26]:
#1D

In [28]:
arr = np.array(my_list)

In [29]:
arr

array([3, 4, 2, 6, 8, 4])

In [30]:
arr1 = np.array([45,23,56,78,9])

In [31]:
arr1

array([45, 23, 56, 78,  9])

In [33]:
type(arr)

numpy.ndarray

In [34]:
type(arr1)

numpy.ndarray

In [35]:
arr1.shape


(5,)

In [36]:
arr.shape

(6,)

In [37]:
arr

array([3, 4, 2, 6, 8, 4])

In [38]:
#2D

In [39]:
my_mat = np.array([[1,2,3],[3,4,7],[6,8,2],[34,7,9]])

In [40]:
my_mat

array([[ 1,  2,  3],
       [ 3,  4,  7],
       [ 6,  8,  2],
       [34,  7,  9]])

In [41]:
type(my_mat)

numpy.ndarray

In [42]:
my_mat.shape

(4, 3)

In [43]:
#(row,column)

In [44]:
my_mat2 = np.array([[2,3],[3,6]])

In [45]:
my_mat2

array([[2, 3],
       [3, 6]])

In [46]:
my_mat2.shape

(2, 2)