In [1]:
import numpy as np

In [2]:
arr1 = np.array([34,56,3,67,23,22,78,9])

In [3]:
arr1.shape

(8,)

In [4]:
arr1[2]

3

In [5]:
arr1[6]

78

In [6]:
arr1[-1]

9

In [7]:
arr1[2:5]

array([ 3, 67, 23])

In [8]:
arr2 = np.array([[2,34,56],[67,34,68],[45,2,7],[48,23,1]])

In [9]:
arr2

array([[ 2, 34, 56],
       [67, 34, 68],
       [45,  2,  7],
       [48, 23,  1]])

In [10]:
arr2.shape

(4, 3)

In [11]:
arr2[1]

array([67, 34, 68])

In [12]:
#arr2[st:end,st:end]

In [13]:
arr2[:,1]

array([34, 34,  2, 23])

In [14]:
arr2[:3,1]

array([34, 34,  2])

In [15]:
arr2

array([[ 2, 34, 56],
       [67, 34, 68],
       [45,  2,  7],
       [48, 23,  1]])

In [16]:
arr2[0:3,1:]

array([[34, 56],
       [34, 68],
       [ 2,  7]])

In [17]:
arr2[1:3]

array([[67, 34, 68],
       [45,  2,  7]])

In [18]:
arr2[1:3,0:2]

array([[67, 34],
       [45,  2]])

In [19]:
import pandas as pd

In [20]:
label = ['a','b','c']

In [21]:
my_data = [45,65,8]

In [22]:
arr = np.array([89,5,6])

In [23]:
d = {'x':34,'y':67,'z':56}

In [24]:
d

{'x': 34, 'y': 67, 'z': 56}

In [27]:
ser1 = pd.Series(my_data)

In [28]:
ser1

0    45
1    65
2     8
dtype: int64

In [29]:
ser2 = pd.Series(my_data,index=label)

In [30]:
ser2

a    45
b    65
c     8
dtype: int64

In [31]:
ser2 = pd.Series(d)

In [32]:
ser2

x    34
y    67
z    56
dtype: int64

In [33]:
ser3 = pd.Series([45,89,6,87,69])

In [34]:
ser3

0    45
1    89
2     6
3    87
4    69
dtype: int64

In [35]:
#Datafram

In [36]:
df = pd.DataFrame(np.random.rand(5,4),columns=['drusti','avanti','akshata','prajawal'],index=['a','b','x','y','z'])

In [37]:
df

drusti    avanti   akshata  prajawal
a  0.312543  0.108644  0.888832  0.239917
b  0.987882  0.211545  0.757155  0.207747
x  0.907623  0.263075  0.327142  0.965339
y  0.815577  0.111513  0.862501  0.577695
z  0.456181  0.583222  0.918884  0.885612

In [38]:
df.shape

(5, 4)

In [42]:
df1 =pd.read_csv('sat.csv')

In [43]:
df1

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [44]:
df2 = pd.read_csv('test.csv',names=['name','salary','city'])

In [45]:
df2

name  salary    city
0   avanti    5000  nagpur
1  prajwal    5678   akola
2  drushti    7899    pune
3  akshata  345566   delhi